### ISSUE TITLE
Move bundler/setup to Rakefile from spec_helper/test_helper

### ISSUE THREAD

**Issue by pravi** [rubocop-hq/packaging-style-guide#5]
Many gems do this already, for example puma, ruby-shoulda-context etc. If the bundler/setup require is part of tests, we have to patch it, but having it in Rakefile avoids having to maintain a patch but upstream does not lose out anything as their existing workflow will continue to work.

**Comment by utkarsh2102** [comment]
Hey,

Using "bundler/setup" is redundant in tests. We're just removing it's usage altogether.
See here: https://github.com/utkarsh2102/rubocop-packaging/pull/18

This cop will be shortly released once I migrate the documentation from packaging-style-guide to the docs/ in rubocop-packaging, which should be happening soon!

Please let me know if you want to propose something different?
If not, do you think we can close this issue here in the favor of https://github.com/utkarsh2102/rubocop-packaging/pull/18 being released soon?

**Comment by pravi** [comment]
Sounds good.
